### ISSUE TITLE
Implement authorization code grant in Northstar-PHP/Aurora.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/TeamRocket#27]
This is an ✨extra ✨ story since we (hopefully!) are not going to dive into all the extra work required to get Northstar login working inside an `iframe` for #13. Instead, let's use that time to get a head start on Laravel implementation for our single sign-on. 😄

**Comment by DFurnes** [comment]
This was completed in DoSomething/gateway#32 and DoSomething/aurora#150.

**Comment by jessleenyc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) As an engineer, I want to update oauth password grant on Aurora to oauth code grant so that we're authenticating users consistently across browsers.](https://trello.com/c/Vpc31SD1/68-5-as-an-engineer-i-want-to-update-oauth-password-grant-on-aurora-to-oauth-code-grant-so-that-we-re-authenticating-users-consiste)
